name: diz_core_storage_reader
description: Simple universal storage reader for debug
version: 1.0.0
repository: https://github.com/DizoftTeam/diz-core-storage-reader

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
